#!/usr/bin/php
<?php
include("dhcp-parser.php");
if(is_file("/etc/dhcp-tools.conf")){
  include("/etc/dhcp-tools.conf");
} else {
  define('configfile','/etc/dhcp/dhcpd.conf');
  define('leases','/var/lib/dhcp/dhcpd.leases');
  define('networkexclude','||');
  define('aggregatelans','w-lan-core');
  define('error',50);
  define('warn',35);
}

$dataset=fetchdata(configfile,leases,networkexclude);

$poolwarning="";
$poolerror="";

// aggregate networks
$lans=array_keys($dataset);
foreach(explode(",",aggregatelans) as $lan){
  $dataset[$lan]=array();
  foreach(preg_grep("/^$lan.+/",$lans) as $lanname){
    foreach($dataset[$lanname] as $key=>$value){
      if(!isset($dataset[$lan][$key])){
	$dataset[$lan][$key]=0;
      }
      $dataset[$lan][$key]+=$value;
    }
    unset($dataset[$lanname]);
  }
}

foreach($dataset as $name=>$pool){
  // $name=strtr($name,"-","_"); geen idee waarom ik dit had
  if($pool['dhcptotal']!=0) {
    $value=((($pool['dhcptotal']-$pool['dhcpfree']-$pool['dhcpbackup'])/$pool['dhcptotal'])*100);
    if($value>error){
      $poolerror.=sprintf("%s: %.2f%% ",$name,$value);
    } else {
      if($value>warn){
        $poolwarning.=sprintf("%s: %.2f%% ",$name,$value);
      }
    }
  }  
}

if($poolwarning!="") echo "warning: $poolwarning ";
if($poolerror!="") echo "error: $poolerror ";
if($poolwarning=="" and $poolerror=="") echo "dhcp pools are ok";
if($poolerror!="") exit(2);
if($poolwarning!="") exit(1);  
exit(0);
